/**
 * Short topic labels for KSH articles without commentary (Tier B), used in
 * page titles, chips and the JSON contract. Each label paraphrases the
 * article's official wording — keep it factual. Articles missing here fall
 * back to the title of their Oddział/Rozdział.
 */
export const KSH_ARTICLE_TOPICS: Record<string, string> = {
  '15': 'kredyt, pożyczka i poręczenie dla członka organu spółki',
  '17': 'czynność prawna bez wymaganej uchwały',
  '18': 'kto może być członkiem zarządu i rady nadzorczej',
  '154': 'minimalny kapitał zakładowy i wartość udziału',
  '156': 'jedyny wspólnik zamiast zgromadzenia wspólników',
  '173': 'oświadczenia jedynego wspólnika wobec spółki',
  '177': 'dopłaty wspólników',
  '178': 'wysokość i terminy dopłat',
  '179': 'zwrot dopłat',
  '191': 'prawo do udziału w zysku',
  '193': 'dzień dywidendy i uprawnieni do dywidendy',
  '195': 'zaliczka na poczet dywidendy',
  '201': 'zarząd – skład, powołanie i odwołanie',
  '202': 'kadencja i wygaśnięcie mandatu członka zarządu',
  '203': 'odwołanie członka zarządu',
  '204': 'zakres prawa do reprezentacji spółki',
  '205': 'sposób reprezentacji przy wieloosobowym zarządzie',
  '206': 'dane obowiązkowe na pismach i stronie spółki',
  '208': 'prowadzenie spraw spółki i uchwały zarządu',
  '209': 'konflikt interesów członka zarządu',
  '211': 'zakaz konkurencji członka zarządu',
  '213': 'rada nadzorcza i komisja rewizyjna',
  '227': 'podejmowanie uchwał wspólników (także pisemnie)',
  '228': 'sprawy wymagające uchwały wspólników',
  '230': 'zobowiązanie przekraczające dwukrotność kapitału',
  '231': 'zwyczajne zgromadzenie wspólników',
  '233': 'duża strata w bilansie – obowiązek zwołania zgromadzenia',
  '234': 'miejsce zgromadzenia wspólników',
  '235': 'zwołanie zgromadzenia wspólników',
  '238': 'sposób zwołania zgromadzenia wspólników',
  '240': 'uchwały bez formalnego zwołania zgromadzenia',
  '244': 'wyłączenie wspólnika od głosowania',
  '245': 'większość głosów przy uchwałach wspólników',
  '246': 'uchwały wymagające kwalifikowanej większości',
  '247': 'głosowanie jawne i tajne',
  '248': 'protokół i księga protokołów',
  '249': 'powództwo o uchylenie uchwały wspólników',
  '252': 'powództwo o stwierdzenie nieważności uchwały',
  '253': 'reprezentacja spółki w sporze o uchwałę wspólników',
  '293': 'odpowiedzialność członków organów wobec spółki',
  '299': 'odpowiedzialność członków zarządu za zobowiązania spółki',
  '379': 'umowa spółki akcyjnej z członkiem zarządu',
  '551': 'przekształcenia spółek i przedsiębiorcy',
};
