import type { WikiEntityType } from '@/lib/wiki-fallback';

// ─── Statute layer (generated by scripts/ksh/ingest-ksh.mjs) ─────────────────

export type KshUnitType = 'para' | 'pint' | 'lett' | 'tire' | 'pass' | 'other';

export type KshTextBlock = { type: 'text'; text: string };

export type KshUnit = {
  type: KshUnitType;
  /** Machine symbol: "1", "1-1" (§ 1¹), "a". */
  symbol: string;
  /** Display symbol: "1", "1¹", "a". */
  label: string;
  content: KshBlock[];
};

export type KshBlock = KshTextBlock | KshUnit;

export type KshStatuteArticle = {
  /** Machine number: "210", "300-1" (art. 300¹). */
  number: string;
  /** "Art. 210", "Art. 300¹". */
  label: string;
  slug: string;
  eliUnitId: string;
  /** Structural ancestry ids (Tytuł → Dział → Rozdział → Oddział). */
  path: string[];
  repealed: boolean;
  content: KshBlock[];
  /** Official footnotes (e.g. Constitutional Tribunal annotations). */
  footnotes: string[];
  textSha256: string;
};

export type KshStructureUnit = {
  id: string;
  kind: 'titl' | 'bran' | 'chpt' | 'schp';
  label: string;
  title: string;
  parent: string | null;
};

export type KshStatuteSnapshot = {
  generatedAt: string;
  act: {
    name: string;
    shortName: string;
    title: string;
    eli: string;
    isapUrl: string;
    inForce: string;
    eliChangeDate: string;
  };
  consolidatedText: {
    eli: string;
    citation: string;
    title: string;
    announcementDate: string;
    isapUrl: string;
    sourceSha256: string;
  };
  amendingActsSeen: { eli: string; date: string }[];
  structure: KshStructureUnit[];
  order: string[];
  articles: Record<string, KshStatuteArticle>;
};

// ─── Amendments published after the consolidated text ───────────────────────

export type KshAmendment = {
  /** ELI id, e.g. "DU/2026/176". */
  eli: string;
  citation: string;
  title: string;
  kind: 'statute' | 'constitutional-tribunal';
  /** Date the KSH changes take effect (earliest, if staggered). */
  effectiveFrom: string;
  /** Article numbers touched (machine form, e.g. "300-32"). */
  articles: string[];
  /** Short plain-language note shown on affected article pages. */
  note: string;
  /**
   * `pending` — not yet in force: shown as an upcoming-change banner.
   * `applied` — in force AND reflected in reviewed article versions (lib/ksh/versions).
   * `annotation` — does not change wording (e.g. interpretive TK ruling); shown as a note.
   */
  status: 'pending' | 'applied' | 'annotation';
};

// ─── Editorial layer ────────────────────────────────────────────────────────

/**
 * A — rich commentary, indexed, in sitemap.
 * B — short reference page, `noindex, follow` until commentary is added.
 */
export type KshTier = 'A' | 'B';

export type KshCaseLaw = {
  court: string;
  date: string;
  signature: string;
  holding: string;
  url?: string;
};

export type KshCommentary = {
  article: string;
  tier: KshTier;
  /** Short topic used in titles: "umowa między spółką a członkiem zarządu". */
  topic: string;
  /** SEO <title> without brand suffix. */
  seoTitle: string;
  metaDescription: string;
  /** 2–3 sentence plain-language summary shown under the H1. */
  summary: string;
  /** One-line answer to "what does this mean for me". */
  keyTakeaway: string;
  /** Markdown sections — citations inside are auto-linked. */
  explanation: string;
  appliesWhen: string[];
  doesNotApply?: string[];
  examples: { title: string; body: string }[];
  mistakes: { title: string; body: string }[];
  whatToDo: string[];
  documents: { label: string; description: string; href?: string }[];
  caseLaw?: KshCaseLaw[];
  faq: { question: string; answer: string }[];
  relatedArticles: string[];
  /** Pinned poradnik slugs (auto-detected citing guides are appended). */
  relatedGuides: string[];
  appActions: { label: string; href: string; description?: string }[];
  entityTypes: WikiEntityType[];
  topics: string[];
  verification: {
    /** Must equal the statute article's textSha256 — build fails otherwise. */
    statuteSha256: string;
    lastVerifiedAt: string;
    /** `editorial` = written/checked by KsięgaI team; `legal` = reviewed by a lawyer. */
    reviewStatus: 'editorial' | 'legal';
  };
  publishedAt: string;
  updatedAt: string;
};
